stages:
  standalone_retriever:
    cmd: python ./evals/Component_level/0_retriever.py
    deps:
      - ./evals/Component_level/0_retriever.py
      - ./data/sample_test_set.csv       
    params:
      - standalone_retriever.test_set
      - standalone_retriever.output
      - standalone_retriever.vector_store_name
      - standalone_retriever.vector_store_collection_name
      - standalone_retriever.search_type
      - standalone_retriever.k
      - standalone_retriever.embeddings.model_name
      - standalone_retriever.models.region
      - standalone_retriever.region
      - standalone_retriever.llm_model_id
      - standalone_retriever.llm_temperature
      - standalone_retriever.RECALL_THRESHOLD
      - standalone_retriever.PRECISION_THRESHOLD
      - standalone_retriever.name
    outs:
      - ./data/standalone_retriever_eval.csv

  standalone_generator:
    cmd: python ./evals/Component_level/1_generator.py
    deps:
      - ./evals/Component_level/1_generator.py
      - ./data/sample_test_set.csv
    params:
      - standalone_generator.test_set
      - standalone_generator.output
      - standalone_generator.vector_store_name
      - standalone_generator.vector_store_collection_name
      - standalone_generator.search_type
      - standalone_generator.k
      - standalone_generator.embeddings.model_name
      - standalone_generator.models.region
      - standalone_generator.region
      - standalone_generator.llm_model_id
      - standalone_generator.llm_temperature
      - standalone_generator.FAITHFULNESS_THRESHOLD
      - standalone_generator.ANSWER_RELEVANCY_THRESHOLD
      - standalone_generator.name
    outs:
      - ./data/standalone_generator_eval.csv

  pipeline_eval:
    cmd: python ./evals/PipelineLevel/eval.py
    deps:
      - ./evals/PipelineLevel/eval.py
      - ./data/sample_test_set.csv
      - ./src/workflow
    params:
      - pipeline_eval.test_set
      - pipeline_eval.output
      - pipeline_eval.vector_store_name
      - pipeline_eval.vector_store_collection_name
      - pipeline_eval.search_type
      - pipeline_eval.k
      - pipeline_eval.embeddings.model_name
      - pipeline_eval.models.region
      - pipeline_eval.region
      - pipeline_eval.llm_model_id
      - pipeline_eval.llm_temperature
      - pipeline_eval.RECALL_THRESHOLD
      - pipeline_eval.PRECISION_THRESHOLD
      - pipeline_eval.FAITHFULNESS_THRESHOLD
      - pipeline_eval.ANSWER_RELEVANCY_THRESHOLD
      - pipeline_eval.CONTEXTUAL_RELEVANCY_THRESHOLD
      - pipeline_eval.name
    outs:
      - ./data/pipeline_eval.csv